/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScratchRouteImport } from './routes/scratch'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ScratchRoute = ScratchRouteImport.update({
  id: '/scratch',
  path: '/scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compose': typeof ComposeRoute
  '/connect': typeof ConnectRoute
  '/debug': typeof DebugRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/scratch': typeof ScratchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compose': typeof ComposeRoute
  '/connect': typeof ConnectRoute
  '/debug': typeof DebugRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/scratch': typeof ScratchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compose': typeof ComposeRoute
  '/connect': typeof ConnectRoute
  '/debug': typeof DebugRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/scratch': typeof ScratchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compose'
    | '/connect'
    | '/debug'
    | '/how-it-works'
    | '/lab'
    | '/login'
    | '/onboarding'
    | '/scratch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compose'
    | '/connect'
    | '/debug'
    | '/how-it-works'
    | '/lab'
    | '/login'
    | '/onboarding'
    | '/scratch'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compose'
    | '/connect'
    | '/debug'
    | '/how-it-works'
    | '/lab'
    | '/login'
    | '/onboarding'
    | '/scratch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComposeRoute: typeof ComposeRoute
  ConnectRoute: typeof ConnectRoute
  DebugRoute: typeof DebugRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ScratchRoute: typeof ScratchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scratch': {
      id: '/scratch'
      path: '/scratch'
      fullPath: '/scratch'
      preLoaderRoute: typeof ScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComposeRoute: ComposeRoute,
  ConnectRoute: ConnectRoute,
  DebugRoute: DebugRoute,
  HowItWorksRoute: HowItWorksRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ScratchRoute: ScratchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
